name: unumondo
favicon: null
layout_spectrum: 0.99407
typography_spectrum: 0.40026
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8125
  lightness: 0.4878087155520916
  saturation: 0.8519057631492615
  rhythmicContrast: 0.8716904888860881
purpose: []
